# Generated by Django 5.1.4 on 2025-02-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [("can_block_user", "Can block user")],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
