# Generated by Django 5.1.4 on 2025-02-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user should be treated as active."
                          "Unselect this instead of deleting accounts.",
            ),
        ),
    ]
