# Generated by Django 5.1.4 on 2025-01-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_mailing_start_send_alter_mailing_stop_send"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("processing", "Запущена"),
                    ("completed", "Завершена"),
                ],
                default="Создана",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
